# Generated by Django 4.0 on 2021-12-08 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='authuser',
            table='user',
        ),
    ]
